database:
    host: 127.0.0.1
    port: 5456
    name: caweb1_1_0
    pass-dir: dist/.db/caweb1_1_0
    auth-method: scram-sha-256
gin:
    logger: true
    recovery: true
usecases:
    cars:
        delay-of-old-parking-method: 15s
versions:
    database: 1.1.0
    config: 2.0.0
