# Copyright (c) 2024 Behnam Momeni
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
database:
    # host IP address or name, although IP should be preferred as it
    # requires no translation (even localhost from the /etc/hosts file)
    host: 127.0.0.1
    # port number
    port: 5456
    # database name which should contain complete semantic version
    name: caweb1_2_0
    # passwords directory should contain a .pgpass or .pgpass.new file
    # containing the PostgreSQL standard password lines following this
    # format:  127.0.0.1:5456:caweb1_0_0:caweb:tHePaSsWoRd
    pass-dir: dist/.db/caweb1_2_0
    auth-method: scram-sha-256
gin:
    logger: true
    recovery: true
# The use cases specific configuration items are kept here which are
# used for instantiation of those use cases. Although it works well
# in this sample project, in a larger scale project, a different
# set of categories which do not necessarily align with the use cases
# may be useful. So, consider your project requirements and find
# their natural configuration settings categories.
usecases:
    cars:
        delay-of-old-parking-method: 15s
        # the inclusive minimum value which may be used for the
        # delay-of-old-parking-method setting (which will be unrestricted
        # by default, if commented out)
        delay-of-old-parking-method-minimum: 1s
        # the inclusive maximum value which may be used for the
        # delay-of-old-parking-method setting (which will be unrestricted
        # by default, if commented out)
        delay-of-old-parking-method-maximum: 5m
# Versions are not settings themselves. For example, if we were talking
# about the caweb Golang module version, it would find its place in a
# const definition in some package (to be printed by a "version" command
# as an example). However, following settings provide hints to know how
# other settings are formatted. That is, a loader needs to check the
# config version before knowing that "old-parking-method-delay" field
# should be expected or "delay-of-old-parking-method" field. Similarly,
# the database version informs us that which tables with which columns
# are expected to be seen, so a proper migration plan may be set.
# In this sense, these settings are immutable.
versions:
    # semantic version of the database schema
    database: 1.2.0
    # semantic version of the configuration file itself
    config: 2.1.0
