---
database:
  host: 127.0.0.1
  port: 5432
  name: caweb1_0_0
  role: caweb
  pass-file: dist/.db/caweb1_0_0/caweb.pass
gin:
  logger: true
  recovery: true
usecases:
  cars:
    old-parking-method-delay: 15s
