# Copyright (c) 2024 Behnam Momeni
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

database:
    host: 127.0.0.1
    port: 5456
    name: caweb1_1_0
    pass-dir: dist/.db/caweb1_1_0
    auth-method: scram-sha-256
gin:
    logger: true
    recovery: true
usecases:
    cars:
        delay-of-old-parking-method: 15s
versions:
    database: 1.1.0
    config: 2.0.0
